### ISSUE TITLE
Feature request: customizable VIDEO PORT setting

### ISSUE THREAD

**Issue by lyusupov** [Consti10/FPV_VR#2]
I've found out that most UDP input ports of the App are customizable.
Most but not the VIDEO PORT. It looks hardwired to 5000.
This causes a conflict with Mission Planner (or Tower) under certain conditions.

I use gstreamer to supply both raw and RTP streams. I want to feed simultaneously RTP stream over port 5000 for MP and the RAW stream over any other available port.
 
My suggestion is to alter the VIDEO PORT meaning from a constant onto variable which can be configured in 'Settings' menu. By default, VIDEO PORT variable's value is 5000.

**Comment by Consti10** [comment]
changed in FPV_VR 2018
