### ISSUE TITLE
App crashed in Stereomode

### ISSUE THREAD

**Issue by AlanJan** [Consti10/FPV_VR#4]
Hi,
When i run the app in video only, it works fine.
But When i run with osd then the app will crash.
In stereomode it will crash as well.
Can you add the option stereo without osd?
I use it with a Sony Xperia z5 premium E6853 with android 7.1.1
With FPV_VR 2018
Thanks

**Comment by Consti10** [comment]
Hello AlanJan,
I'm sorry to hear that.
Have you tried disabling all OSD elements in "General OSD Settings" ?

Also, maybe disable "Head tracking" if enabled.

I would rather fix the bug causing the OSD to crash on the Xperia z5. Can
you send a bug report when the app crashes ? I don't have anything in my
developer console yet.

I will have a look into it as soon as possible, but I may need your help.
This seems to be device specific.

Best regards,
Constantin

**Comment by AlanJan** [comment]
Hi Constantin,
Thanks for your quick reply!

Yes, i have all the osd and headtracking options disabled but with no luck.
Where can i find the debug logging?

Regards,
Alan

**Comment by Consti10** [comment]
They will be send automatically if you opted in to "automatically share
usage and diagnostic data" when setting up your android. Don't know how to
send them without.

But It is really likely that it only takes some h until I have this data
displayed. I will look again tomorrow.

**Comment by AlanJan** [comment]
Okay, i have tested without wifi so i switch it on right now, does the app resent the data?

**Comment by Consti10** [comment]
Since this is handled internally by google and not "live", rather like "
update once every hour" I can't tell. But reproducing the crash with WiFi
on is definitely a good thing

**Comment by Consti10** [comment]
Hello AlanJan,
It looks like you are using the old version of FPV_VR. At least we are in the deprecated github branch.  FPV_VR 2018 btw. FPV-VR for wifibroadcast 2018 is the latest version.
Check out FPV_VR 2018 on github for the opened source code with a delay in updates or
Buy FPV-VR for wifibroadcast 2018 from the play storeto get the latest version and support developement. Crash analysis is also only available when bought from the app store.
Thanks

**Comment by AlanJan** [comment]
I have buy the app from the store, now it works fine! Thanks for your help.

Regards,
Alan

**Comment by Consti10** [comment]
Glad to hear that.
